services:
  hhvm:
    container_name: theodore-portable-hack-ast-linters-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /mnt/project
    ports:
      - 48551:10641
